### ISSUE TITLE
Landing or Gateway pages

### ISSUE THREAD

**Issue by KevinJump** [KevinJump/LocalGovStarterKit#1]
I am still unsure about the internal naming of the _gateway pages_ within the starter kit.  

![Gateway-Landing](http://blog.jumoo.co.uk/wp-content/uploads/2015/07/gatewaypage.png)

Previously they were _Landing Pages_, but as they weren't necessarily pages built for people to land on the name didn't seem to fit. They are pages that offer a gateway to more content, hence their name now. 

However I wonder if the term Landing page has now become much more synonymous with this type of page and it would make more sense to most people for it to be called a landing page?

**Comment by leekelleher** [comment]
+1 on "Gateway Page" :+1: 

Reason being, "Gateway Page" feels more semantic in the context of the website; is in, a user comes to the page and is presented with deeper content sections.

To me "Landing Page" has more of a marketing feel to it, I'd expect CTAs, goals; leading the user somewhere, rather than offering multiple options.

**Comment by KevinJump** [comment]
called gateway pages now :)
